### ISSUE TITLE
Bascic React sceleton & webpack config

### ISSUE THREAD

**Issue by benbieler** [SocialDocs/SocialDocs#4]
- [ ] Webpack setup
- [ ] Basic React + Flux setup
- [ ] React router (Home: "/")

**Comment by Ma27** [comment]
I assume we need something like this: https://github.com/Sententiaregum/Sententiaregum/blob/master/webpack.factory.js

**Comment by benbieler** [comment]
:+1:  i'll look in to this...

**Comment by Ma27** [comment]
ok. One thing you could also do would be creating a ``sententiaregum/webpack-scaffolding`` package for npm and use this package in both projects

**Comment by benbieler** [comment]
I don't think this is necessary. I mean we are talking about 3 files, which are very simple to set up...
